# Generated by Django 4.2.4 on 2023-08-05 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

  initial = True

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      ('auth', '0012_alter_user_first_name_max_length'),
  ]

  operations = [
      migrations.CreateModel(
          name='Address',
          fields=[
              ('building', models.CharField(blank=True, max_length=50, null=True)),
              ('street', models.CharField(blank=True, max_length=50, null=True)),
              ('branches_from', models.CharField(
                  blank=True, max_length=50, null=True)),
              ('floor', models.CharField(blank=True, max_length=50, null=True)),
              ('apartment_number', models.CharField(
                  blank=True, max_length=50, null=True)),
              ('residential_complexes', models.CharField(
                  blank=True, max_length=50, null=True)),
              ('district', models.CharField(blank=True, max_length=50, null=True)),
              ('additional_details', models.TextField(
                  blank=True, max_length=500, null=True)),
              ('id', models.UUIDField(default=uuid.uuid4, editable=False,
               primary_key=True, serialize=False, unique=True)),
          ],
      ),
      migrations.CreateModel(
          name='Profile',
          fields=[
              ('name', models.CharField(max_length=200, unique=True)),
              ('birthdate', models.DateField(null=True)),
              ('current_talmza_level_year',
               models.IntegerField(default=1, null=True)),
              ('current_school_level_year', models.IntegerField(
                  blank=True, default=1, null=True)),
              ('job', models.CharField(blank=True, max_length=200, null=True)),
              ('gender', models.CharField(
                  choices=[('M', 'ذكر'), ('F', 'أنثي')], default=('M', 'ذكر'), max_length=1)),
              ('phone_number', models.CharField(
                  blank=True, max_length=11, null=True)),
              ('father_phone_number', models.CharField(
                  blank=True, max_length=11, null=True)),
              ('mother_phone_number', models.CharField(
                  blank=True, max_length=11, null=True)),
              ('mobile_follow_up_on_WhatsApp', models.CharField(
                  blank=True, max_length=11, null=True)),
              ('confession_father', models.CharField(
                  blank=True, max_length=200, null=True)),
              ('church', models.CharField(
                  default='كنيسة السيدة العذراء مريم و الشهيد مارجرجس بغبريال', max_length=200)),
              ('deaconess', models.CharField(choices=[
               ('غير', 'غير مرشوم'), ('أغس', 'أغنسطس'), ('إبس', 'إبسالطس')], max_length=10)),
              ('profile_image', models.ImageField(
                  blank=True, default='images/profiles/user-default.png', null=True, upload_to='images/profiles')),
              ('id', models.UUIDField(default=uuid.uuid4, editable=False,
               primary_key=True, serialize=False, unique=True)),
              ('address', models.OneToOneField(blank=True, null=True,
               on_delete=django.db.models.deletion.SET_NULL, to='users.address')),
          ],
      ),
      migrations.CreateModel(
          name='UserPermissionTag',
          fields=[
              ('tag_name', models.CharField(max_length=100, unique=True)),
              ('id', models.UUIDField(default=uuid.uuid4, editable=False,
               primary_key=True, serialize=False, unique=True)),
              ('permissions', models.ManyToManyField(to='auth.permission')),
          ],
      ),
      migrations.CreateModel(
          name='TalmzaLevel',
          fields=[
              ('level_name', models.CharField(max_length=50)),
              ('level_number', models.IntegerField()),
              ('number_of_years', models.IntegerField(default=2)),
              ('id', models.UUIDField(default=uuid.uuid4, editable=False,
               primary_key=True, serialize=False, unique=True)),
              ('next_level', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
               related_name='talmza_next_level', to='users.talmzalevel')),
              ('previous_level', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
               related_name='talmza_previous_level', to='users.talmzalevel')),
          ],
          options={
              'ordering': ['level_number'],
          },
      ),
      migrations.CreateModel(
          name='SchoolLevel',
          fields=[
              ('level_name', models.CharField(max_length=50)),
              ('level_number', models.IntegerField()),
              ('number_of_years', models.IntegerField(blank=True, null=True)),
              ('id', models.UUIDField(default=uuid.uuid4, editable=False,
               primary_key=True, serialize=False, unique=True)),
              ('next_level', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
               related_name='school_next_level', to='users.schoollevel')),
              ('previous_level', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
               related_name='school_previous_level', to='users.schoollevel')),
          ],
          options={
              'ordering': ['level_number'],
          },
      ),
      migrations.CreateModel(
          name='ProfileFormLog',
          fields=[
              ('log_date', models.DateTimeField(auto_now_add=True)),
              ('category_action', models.CharField(
                  choices=[('D', 'Delete'), ('A', 'ADD'), ('E', 'Edit')], max_length=1)),
              ('action', models.TextField(max_length=2000)),
              ('id', models.UUIDField(default=uuid.uuid4, editable=False,
               primary_key=True, serialize=False, unique=True)),
              ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
               related_name='created_by', to='users.profile')),
              ('created_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
               related_name='created_for', to='users.profile')),
          ],
      ),
      migrations.AddField(
          model_name='profile',
          name='school_level',
          field=models.ForeignKey(
              null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.schoollevel'),
      ),
      migrations.AddField(
          model_name='profile',
          name='talmza_level',
          field=models.ForeignKey(
              null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.talmzalevel'),
      ),
      migrations.AddField(
          model_name='profile',
          name='user',
          field=models.OneToOneField(
              null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
      ),
      migrations.CreateModel(
          name='ExpensesProfileForm',
          fields=[
              ('year', models.CharField(max_length=4)),
              ('amount_of_money_payed', models.IntegerField()),
              ('id', models.UUIDField(default=uuid.uuid4, editable=False,
               primary_key=True, serialize=False, unique=True)),
              ('created_for', models.ForeignKey(
                  null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
          ],
      ),
  ]
