# Generated by Django 4.2.4 on 2023-08-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_custom_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoollevel',
            name='prevues_level',
        ),
        migrations.RemoveField(
            model_name='talmzalevel',
            name='prevues_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permission_tags',
            field=models.ManyToManyField(blank=True, null=True, to='users.userpermissiontag'),
        ),
        migrations.AddField(
            model_name='schoollevel',
            name='previous_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_previous_level', to='users.schoollevel'),
        ),
        migrations.AddField(
            model_name='talmzalevel',
            name='previous_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talmza_previous_level', to='users.talmzalevel'),
        ),
        migrations.AddField(
            model_name='userpermissiontag',
            name='next_Tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_tag', to='users.userpermissiontag'),
        ),
        migrations.AddField(
            model_name='userpermissiontag',
            name='previous_Tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_tag', to='users.userpermissiontag'),
        ),
    ]
