# Generated by Django 4.2.4 on 2023-08-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_schoollevel_prevues_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissiontag',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tag', to='users.userpermissiontag'),
        ),
        migrations.AlterField(
            model_name='userpermissiontag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_tag', to='users.userpermissiontag'),
        ),
    ]
