# Generated by Django 4.2.4 on 2023-09-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_highest_tag_profile_highest_tag_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="highest_tag_level",
        ),
    ]
