# Generated by Django 4.2.4 on 2023-08-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userpermissiontag_next_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissiontag',
            name='is_buttom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissiontag',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
