# Generated by Django 4.2.3 on 2023-07-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentSchoolLevelYear',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='currentTalmzaLevelYear',
            field=models.IntegerField(default=1),
        ),
    ]
