# Generated by Django 4.2.3 on 2023-07-29 19:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_currentschoollevelyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalmzaLevel',
            fields=[
                ('level_name', models.CharField(max_length=20)),
                ('level_number', models.IntegerField()),
                ('number_of_years', models.IntegerField(default=2)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('next_level', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.talmzalevel')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('level_name', models.CharField(max_length=20)),
                ('level_number', models.IntegerField()),
                ('number_of_years', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('next_level', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.schoollevel')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='school_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.schoollevel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='talmza_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.talmzalevel'),
        ),
    ]
