# Generated by Django 4.2.4 on 2023-10-06 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userpermissiontag_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[("liturgy", "القداس"), ("hymnClass", "حصة الألحان")],
                        default="liturgy",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("attendance", "حضور"), ("late", "تأخير")],
                        default="attendance",
                        max_length=50,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "attendance_date", "attendance_type")},
            },
        ),
    ]
