# Generated by Django 4.2.3 on 2023-07-29 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_talmzalevel_schoollevel_profile_school_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFormLog',
            fields=[
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('category_action', models.CharField(choices=[('D', 'Delete'), ('A', 'ADD'), ('E', 'Edit')], max_length=1)),
                ('action', models.TextField(max_length=2000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='users.profile')),
                ('created_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_for', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MasreefProfileForm',
            fields=[
                ('year', models.CharField(max_length=4)),
                ('amount_of_money_payed', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
