# Generated by Django 4.2.3 on 2023-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profileformlog_masreefprofileform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollevel',
            name='number_of_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
