# Generated by Django 4.2.3 on 2023-07-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_birthdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasreefProfileForm',
            new_name='ExpensesProfileForm',
        ),
    ]
