# Generated by Django 4.2.3 on 2023-07-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_masreefprofileform_expensesprofileform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deaconess',
            field=models.CharField(choices=[('غير', 'غير مرشوم'), ('أغس', 'أغنسطس'), ('إبس', 'إبسالطس')], max_length=10),
        ),
    ]
