# Generated by Django 4.2.3 on 2023-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_address_additional_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollevel',
            name='level_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='talmzalevel',
            name='level_name',
            field=models.CharField(max_length=50),
        ),
    ]
