# Generated by Django 4.2.3 on 2023-07-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_schoollevel_level_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollevel',
            name='prevues_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_prevues_level', to='users.schoollevel'),
        ),
        migrations.AddField(
            model_name='talmzalevel',
            name='prevues_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talmza_prevues_level', to='users.talmzalevel'),
        ),
        migrations.AlterField(
            model_name='schoollevel',
            name='next_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_next_level', to='users.schoollevel'),
        ),
        migrations.AlterField(
            model_name='talmzalevel',
            name='next_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talmza_next_level', to='users.talmzalevel'),
        ),
    ]
