# Generated by Django 4.2.3 on 2023-07-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_schoollevel_prevues_level_talmzalevel_prevues_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoollevel',
            options={'ordering': ['level_number']},
        ),
        migrations.AlterModelOptions(
            name='talmzalevel',
            options={'ordering': ['level_number']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='currentSchoolLevelYear',
            new_name='current_school_level_year',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='currentTalmzaLevelYear',
            new_name='current_talmza_level_year',
        ),
    ]
