# Generated by Django 4.2.3 on 2023-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_schoollevel_options_alter_talmzalevel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='confessionFather',
            new_name='confession_father',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'مذكر'), ('F', 'مؤنث')], max_length=1),
        ),
    ]
