# Generated by Django 4.2.3 on 2023-08-02 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_rename_confessionfather_profile_confession_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.schoollevel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='talmza_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.talmzalevel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
