# Generated by Django 4.2.4 on 2023-08-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_current_school_level_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_talmza_level_year',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثي')], default=('F', 'أنثي'), max_length=1),
        ),
    ]
