# Generated by Django 4.2.4 on 2023-08-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_current_talmza_level_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثي')], default=('M', 'ذكر'), max_length=1),
        ),
    ]
