from .ProfileTestCase.ProfileTests import ProfileTestCase
from .userPermissionTagTestCase.userPermissionTagTests import UserPermissionTagTestCase
from .profileCRUDViewsTestCase.profileCRUDViewsTests import ProfileCRUDViewsTestCase
