# Generated by Django 4.2.4 on 2023-08-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_custom_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoollevel',
            name='prevues_level',
        ),
        migrations.RemoveField(
            model_name='talmzalevel',
            name='prevues_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permission_tags',
            field=models.ManyToManyField(blank=True, to='users.userpermissiontag'),
        ),
        migrations.AddField(
            model_name='schoollevel',
            name='previous_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_previous_level', to='users.schoollevel'),
        ),
        migrations.AddField(
            model_name='talmzalevel',
            name='previous_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talmza_previous_level', to='users.talmzalevel'),
        ),
        migrations.AddField(
            model_name='userpermissiontag',
            name='child',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tag', to='users.userpermissiontag'),
        ),
        migrations.AddField(
            model_name='userpermissiontag',
            name='is_buttom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissiontag',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissiontag',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_tag', to='users.userpermissiontag'),
        ),
        migrations.AlterField(
            model_name='userpermissiontag',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
