# Generated by Django 4.2.4 on 2023-08-09 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userpermissiontag_child_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="current_talmza_level_year",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="talmza_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.talmzalevel",
            ),
        ),
    ]
